### ISSUE TITLE
german KBA import 2023-01

### ISSUE THREAD

**Issue by koaschten** [simonkrauter/Open-EV-Charts#7]
Hi,
let me start by saying, you are doing an awesome job aggregating all the data!

It seems the 2023-01 import of the german KBA data is missing some numbers. at least the small number of EV6 which are in the Data don't show up at https://open-ev-charts.org/#electric-sales:DE:1y:Kia:EV6:table

**Comment by simonkrauter** [comment]
Hi, 
thanks for the feedback.
The Kia EV6 for January Germany is does not up, because it's number (28) is too low. For every month and country the top 50 EV models are listed. Other models are consolidated as "other". I decided for this limit to prevent that the amount of data grows very fast. I hope this explains the issue.

**Comment by simonkrauter** [comment]
Nachtrag: Ich habe nochmal nachgedacht, wie die Situation verbessert werden könnte. Ich habe nun einen Hinweistext eingebaut, der dem Fall von deinem Beispiel auftaucht (commit https://github.com/simonkrauter/Open-EV-Charts/commit/8950360bcad7f0fff667cd89c66586064a1625ac). Ich hoffe der Text ist verständlich.
